# Automatically generated file, do not edit
SET(BII_IS_DEP True)


# LIBRARY latinga_sdl2 ##################################
# with interface latinga_sdl2_interface

# Source code files of the library
SET(BII_LIB_SRC  include/SDL.h
			include/SDL_assert.h
			include/SDL_atomic.h
			include/SDL_audio.h
			include/SDL_bits.h
			include/SDL_blendmode.h
			include/SDL_clipboard.h
			include/SDL_config.h
			include/SDL_config_android.h
			include/SDL_config_iphoneos.h
			include/SDL_config_macosx.h
			include/SDL_config_minimal.h
			include/SDL_config_psp.h
			include/SDL_config_windows.h
			include/SDL_cpuinfo.h
			include/SDL_endian.h
			include/SDL_error.h
			include/SDL_events.h
			include/SDL_filesystem.h
			include/SDL_gamecontroller.h
			include/SDL_gesture.h
			include/SDL_haptic.h
			include/SDL_hints.h
			include/SDL_joystick.h
			include/SDL_keyboard.h
			include/SDL_keycode.h
			include/SDL_loadso.h
			include/SDL_log.h
			include/SDL_main.h
			include/SDL_messagebox.h
			include/SDL_mouse.h
			include/SDL_mutex.h
			include/SDL_name.h
			include/SDL_opengl.h
			include/SDL_opengles.h
			include/SDL_opengles2.h
			include/SDL_pixels.h
			include/SDL_platform.h
			include/SDL_power.h
			include/SDL_quit.h
			include/SDL_rect.h
			include/SDL_render.h
			include/SDL_revision.h
			include/SDL_rwops.h
			include/SDL_scancode.h
			include/SDL_shape.h
			include/SDL_stdinc.h
			include/SDL_surface.h
			include/SDL_system.h
			include/SDL_syswm.h
			include/SDL_thread.h
			include/SDL_timer.h
			include/SDL_touch.h
			include/SDL_types.h
			include/SDL_version.h
			include/SDL_video.h
			include/begin_code.h
			include/close_code.h
			src/SDL.c
			src/SDL_assert.c
			src/SDL_assert_c.h
			src/SDL_error.c
			src/SDL_error_c.h
			src/SDL_hints.c
			src/SDL_log.c
			src/atomic/SDL_atomic.c
			src/atomic/SDL_spinlock.c
			src/audio/SDL_audio.c
			src/audio/SDL_audio_c.h
			src/audio/SDL_audiocvt.c
			src/audio/SDL_audiodev.c
			src/audio/SDL_audiodev_c.h
			src/audio/SDL_audiomem.h
			src/audio/SDL_audiotypecvt.c
			src/audio/SDL_mixer.c
			src/audio/SDL_sysaudio.h
			src/audio/SDL_wave.c
			src/audio/SDL_wave.h
			src/audio/alsa/SDL_alsa_audio.c
			src/audio/alsa/SDL_alsa_audio.h
			src/audio/android/SDL_androidaudio.c
			src/audio/android/SDL_androidaudio.h
			src/audio/arts/SDL_artsaudio.c
			src/audio/arts/SDL_artsaudio.h
			src/audio/baudio/SDL_beaudio.cc
			src/audio/baudio/SDL_beaudio.h
			src/audio/bsd/SDL_bsdaudio.c
			src/audio/bsd/SDL_bsdaudio.h
			src/audio/coreaudio/SDL_coreaudio.c
			src/audio/coreaudio/SDL_coreaudio.h
			src/audio/directsound/SDL_directsound.c
			src/audio/directsound/SDL_directsound.h
			src/audio/directsound/directx.h
			src/audio/disk/SDL_diskaudio.c
			src/audio/disk/SDL_diskaudio.h
			src/audio/dsp/SDL_dspaudio.c
			src/audio/dsp/SDL_dspaudio.h
			src/audio/dummy/SDL_dummyaudio.c
			src/audio/dummy/SDL_dummyaudio.h
			src/audio/esd/SDL_esdaudio.c
			src/audio/esd/SDL_esdaudio.h
			src/audio/fusionsound/SDL_fsaudio.c
			src/audio/fusionsound/SDL_fsaudio.h
			src/audio/nas/SDL_nasaudio.c
			src/audio/nas/SDL_nasaudio.h
			src/audio/paudio/SDL_paudio.c
			src/audio/paudio/SDL_paudio.h
			src/audio/psp/SDL_pspaudio.c
			src/audio/psp/SDL_pspaudio.h
			src/audio/pulseaudio/SDL_pulseaudio.c
			src/audio/pulseaudio/SDL_pulseaudio.h
			src/audio/qsa/SDL_qsa_audio.c
			src/audio/qsa/SDL_qsa_audio.h
			src/audio/sndio/SDL_sndioaudio.c
			src/audio/sndio/SDL_sndioaudio.h
			src/audio/sun/SDL_sunaudio.c
			src/audio/sun/SDL_sunaudio.h
			src/audio/winmm/SDL_winmm.c
			src/audio/winmm/SDL_winmm.h
			src/audio/xaudio2/SDL_xaudio2.c
			src/core/android/SDL_android.c
			src/core/android/SDL_android.cpp
			src/core/android/SDL_android.h
			src/core/linux/SDL_udev.c
			src/core/linux/SDL_udev.h
			src/core/windows/SDL_windows.c
			src/core/windows/SDL_windows.h
			src/cpuinfo/SDL_cpuinfo.c
			src/events/SDL_clipboardevents.c
			src/events/SDL_clipboardevents_c.h
			src/events/SDL_dropevents.c
			src/events/SDL_dropevents_c.h
			src/events/SDL_events.c
			src/events/SDL_events_c.h
			src/events/SDL_gesture.c
			src/events/SDL_gesture_c.h
			src/events/SDL_keyboard.c
			src/events/SDL_keyboard_c.h
			src/events/SDL_mouse.c
			src/events/SDL_mouse_c.h
			src/events/SDL_quit.c
			src/events/SDL_sysevents.h
			src/events/SDL_touch.c
			src/events/SDL_touch_c.h
			src/events/SDL_windowevents.c
			src/events/SDL_windowevents_c.h
			src/events/default_cursor.h
			src/events/scancodes_darwin.h
			src/events/scancodes_linux.h
			src/events/scancodes_windows.h
			src/events/scancodes_xfree86.h
			src/file/SDL_rwops.c
			src/file/cocoa/SDL_rwopsbundlesupport.h
			src/file/cocoa/SDL_rwopsbundlesupport.m
			src/filesystem/beos/SDL_sysfilesystem.cc
			src/filesystem/cocoa/SDL_sysfilesystem.m
			src/filesystem/dummy/SDL_sysfilesystem.c
			src/filesystem/unix/SDL_sysfilesystem.c
			src/filesystem/windows/SDL_sysfilesystem.c
			src/haptic/SDL_haptic.c
			src/haptic/SDL_haptic_c.h
			src/haptic/SDL_syshaptic.h
			src/haptic/darwin/SDL_syshaptic.c
			src/haptic/dummy/SDL_syshaptic.c
			src/haptic/linux/SDL_syshaptic.c
			src/haptic/windows/SDL_syshaptic.c
			src/input/evdev/SDL_evdev.c
			src/input/evdev/SDL_evdev.h
			src/joystick/SDL_gamecontroller.c
			src/joystick/SDL_gamecontrollerdb.h
			src/joystick/SDL_joystick.c
			src/joystick/SDL_joystick_c.h
			src/joystick/SDL_sysjoystick.h
			src/joystick/android/SDL_sysjoystick.c
			src/joystick/beos/SDL_bejoystick.cc
			src/joystick/bsd/SDL_sysjoystick.c
			src/joystick/darwin/SDL_sysjoystick.c
			src/joystick/darwin/SDL_sysjoystick_c.h
			src/joystick/dummy/SDL_sysjoystick.c
			src/joystick/iphoneos/SDLUIAccelerationDelegate.h
			src/joystick/iphoneos/SDLUIAccelerationDelegate.m
			src/joystick/iphoneos/SDL_sysjoystick.m
			src/joystick/linux/SDL_sysjoystick.c
			src/joystick/linux/SDL_sysjoystick_c.h
			src/joystick/psp/SDL_sysjoystick.c
			src/joystick/windows/SDL_dxjoystick.c
			src/joystick/windows/SDL_dxjoystick_c.h
			src/joystick/windows/SDL_mmjoystick.c
			src/libm/e_atan2.c
			src/libm/e_log.c
			src/libm/e_pow.c
			src/libm/e_rem_pio2.c
			src/libm/e_sqrt.c
			src/libm/k_cos.c
			src/libm/k_rem_pio2.c
			src/libm/k_sin.c
			src/libm/math_libm.h
			src/libm/math_private.h
			src/libm/s_atan.c
			src/libm/s_copysign.c
			src/libm/s_cos.c
			src/libm/s_fabs.c
			src/libm/s_floor.c
			src/libm/s_scalbn.c
			src/libm/s_sin.c
			src/loadso/beos/SDL_sysloadso.c
			src/loadso/dlopen/SDL_sysloadso.c
			src/loadso/dummy/SDL_sysloadso.c
			src/loadso/windows/SDL_sysloadso.c
			src/main/beos/SDL_BApp.h
			src/main/beos/SDL_BeApp.cc
			src/main/beos/SDL_BeApp.h
			src/power/SDL_power.c
			src/power/android/SDL_syspower.c
			src/power/beos/SDL_syspower.c
			src/power/linux/SDL_syspower.c
			src/power/macosx/SDL_syspower.c
			src/power/psp/SDL_syspower.c
			src/power/uikit/SDL_syspower.h
			src/power/uikit/SDL_syspower.m
			src/power/windows/SDL_syspower.c
			src/render/SDL_render.c
			src/render/SDL_sysrender.h
			src/render/SDL_yuv_mmx.c
			src/render/SDL_yuv_sw.c
			src/render/SDL_yuv_sw_c.h
			src/render/direct3d/SDL_render_d3d.c
			src/render/mmx.h
			src/render/opengl/SDL_glfuncs.h
			src/render/opengl/SDL_render_gl.c
			src/render/opengl/SDL_shaders_gl.c
			src/render/opengl/SDL_shaders_gl.h
			src/render/opengles/SDL_glesfuncs.h
			src/render/opengles/SDL_render_gles.c
			src/render/opengles2/SDL_gles2funcs.h
			src/render/opengles2/SDL_render_gles2.c
			src/render/opengles2/SDL_shaders_gles2.c
			src/render/opengles2/SDL_shaders_gles2.h
			src/render/psp/SDL_render_psp.c
			src/render/software/SDL_blendfillrect.c
			src/render/software/SDL_blendfillrect.h
			src/render/software/SDL_blendline.c
			src/render/software/SDL_blendline.h
			src/render/software/SDL_blendpoint.c
			src/render/software/SDL_blendpoint.h
			src/render/software/SDL_draw.h
			src/render/software/SDL_drawline.c
			src/render/software/SDL_drawline.h
			src/render/software/SDL_drawpoint.c
			src/render/software/SDL_drawpoint.h
			src/render/software/SDL_render_sw.c
			src/render/software/SDL_render_sw_c.h
			src/render/software/SDL_rotate.c
			src/render/software/SDL_rotate.h
			src/stdlib/SDL_getenv.c
			src/stdlib/SDL_iconv.c
			src/stdlib/SDL_malloc.c
			src/stdlib/SDL_qsort.c
			src/stdlib/SDL_stdlib.c
			src/stdlib/SDL_string.c
			src/thread/SDL_systhread.h
			src/thread/SDL_thread.c
			src/thread/SDL_thread_c.h
			src/thread/beos/SDL_syssem.c
			src/thread/beos/SDL_systhread.c
			src/thread/beos/SDL_systhread_c.h
			src/thread/beos/SDL_systls.c
			src/thread/generic/SDL_syscond.c
			src/thread/generic/SDL_sysmutex.c
			src/thread/generic/SDL_syssem.c
			src/thread/generic/SDL_systhread.c
			src/thread/generic/SDL_systhread_c.h
			src/thread/generic/SDL_systls.c
			src/thread/psp/SDL_syscond.c
			src/thread/psp/SDL_sysmutex.c
			src/thread/psp/SDL_syssem.c
			src/thread/psp/SDL_systhread.c
			src/thread/psp/SDL_systhread_c.h
			src/thread/pthread/SDL_syscond.c
			src/thread/pthread/SDL_sysmutex.c
			src/thread/pthread/SDL_sysmutex_c.h
			src/thread/pthread/SDL_syssem.c
			src/thread/pthread/SDL_systhread.c
			src/thread/pthread/SDL_systhread_c.h
			src/thread/pthread/SDL_systls.c
			src/thread/windows/SDL_sysmutex.c
			src/thread/windows/SDL_syssem.c
			src/thread/windows/SDL_systhread.c
			src/thread/windows/SDL_systhread_c.h
			src/thread/windows/SDL_systls.c
			src/timer/SDL_timer.c
			src/timer/SDL_timer_c.h
			src/timer/beos/SDL_systimer.c
			src/timer/dummy/SDL_systimer.c
			src/timer/psp/SDL_systimer.c
			src/timer/unix/SDL_systimer.c
			src/timer/windows/SDL_systimer.c
			src/video/SDL_RLEaccel.c
			src/video/SDL_RLEaccel_c.h
			src/video/SDL_blit.c
			src/video/SDL_blit.h
			src/video/SDL_blit_0.c
			src/video/SDL_blit_1.c
			src/video/SDL_blit_A.c
			src/video/SDL_blit_N.c
			src/video/SDL_blit_auto.c
			src/video/SDL_blit_auto.h
			src/video/SDL_blit_copy.c
			src/video/SDL_blit_copy.h
			src/video/SDL_blit_slow.c
			src/video/SDL_blit_slow.h
			src/video/SDL_bmp.c
			src/video/SDL_clipboard.c
			src/video/SDL_egl.c
			src/video/SDL_egl.h
			src/video/SDL_fillrect.c
			src/video/SDL_pixels.c
			src/video/SDL_pixels_c.h
			src/video/SDL_rect.c
			src/video/SDL_rect_c.h
			src/video/SDL_shape.c
			src/video/SDL_shape_internals.h
			src/video/SDL_stretch.c
			src/video/SDL_surface.c
			src/video/SDL_sysvideo.h
			src/video/SDL_video.c
			src/video/android/SDL_androidclipboard.c
			src/video/android/SDL_androidclipboard.h
			src/video/android/SDL_androidevents.c
			src/video/android/SDL_androidevents.h
			src/video/android/SDL_androidgl.c
			src/video/android/SDL_androidkeyboard.c
			src/video/android/SDL_androidkeyboard.h
			src/video/android/SDL_androidtouch.c
			src/video/android/SDL_androidtouch.h
			src/video/android/SDL_androidvideo.c
			src/video/android/SDL_androidvideo.h
			src/video/android/SDL_androidwindow.c
			src/video/android/SDL_androidwindow.h
			src/video/bwindow/SDL_BWin.h
			src/video/bwindow/SDL_bclipboard.cc
			src/video/bwindow/SDL_bclipboard.h
			src/video/bwindow/SDL_bevents.cc
			src/video/bwindow/SDL_bevents.h
			src/video/bwindow/SDL_bframebuffer.cc
			src/video/bwindow/SDL_bframebuffer.h
			src/video/bwindow/SDL_bkeyboard.cc
			src/video/bwindow/SDL_bkeyboard.h
			src/video/bwindow/SDL_bmodes.cc
			src/video/bwindow/SDL_bmodes.h
			src/video/bwindow/SDL_bopengl.cc
			src/video/bwindow/SDL_bopengl.h
			src/video/bwindow/SDL_bvideo.cc
			src/video/bwindow/SDL_bvideo.h
			src/video/bwindow/SDL_bwindow.cc
			src/video/bwindow/SDL_bwindow.h
			src/video/cocoa/SDL_cocoaclipboard.h
			src/video/cocoa/SDL_cocoaclipboard.m
			src/video/cocoa/SDL_cocoaevents.h
			src/video/cocoa/SDL_cocoaevents.m
			src/video/cocoa/SDL_cocoakeyboard.h
			src/video/cocoa/SDL_cocoakeyboard.m
			src/video/cocoa/SDL_cocoamessagebox.h
			src/video/cocoa/SDL_cocoamessagebox.m
			src/video/cocoa/SDL_cocoamodes.h
			src/video/cocoa/SDL_cocoamodes.m
			src/video/cocoa/SDL_cocoamouse.h
			src/video/cocoa/SDL_cocoamouse.m
			src/video/cocoa/SDL_cocoamousetap.h
			src/video/cocoa/SDL_cocoamousetap.m
			src/video/cocoa/SDL_cocoaopengl.h
			src/video/cocoa/SDL_cocoaopengl.m
			src/video/cocoa/SDL_cocoashape.h
			src/video/cocoa/SDL_cocoashape.m
			src/video/cocoa/SDL_cocoavideo.h
			src/video/cocoa/SDL_cocoavideo.m
			src/video/cocoa/SDL_cocoawindow.h
			src/video/cocoa/SDL_cocoawindow.m
			src/video/directfb/SDL_DirectFB_WM.c
			src/video/directfb/SDL_DirectFB_WM.h
			src/video/directfb/SDL_DirectFB_dyn.c
			src/video/directfb/SDL_DirectFB_dyn.h
			src/video/directfb/SDL_DirectFB_events.c
			src/video/directfb/SDL_DirectFB_events.h
			src/video/directfb/SDL_DirectFB_modes.c
			src/video/directfb/SDL_DirectFB_modes.h
			src/video/directfb/SDL_DirectFB_mouse.c
			src/video/directfb/SDL_DirectFB_mouse.h
			src/video/directfb/SDL_DirectFB_opengl.c
			src/video/directfb/SDL_DirectFB_opengl.h
			src/video/directfb/SDL_DirectFB_render.c
			src/video/directfb/SDL_DirectFB_render.h
			src/video/directfb/SDL_DirectFB_shape.c
			src/video/directfb/SDL_DirectFB_shape.h
			src/video/directfb/SDL_DirectFB_video.c
			src/video/directfb/SDL_DirectFB_video.h
			src/video/directfb/SDL_DirectFB_window.c
			src/video/directfb/SDL_DirectFB_window.h
			src/video/dummy/SDL_nullevents.c
			src/video/dummy/SDL_nullevents_c.h
			src/video/dummy/SDL_nullframebuffer.c
			src/video/dummy/SDL_nullframebuffer_c.h
			src/video/dummy/SDL_nullvideo.c
			src/video/dummy/SDL_nullvideo.h
			src/video/pandora/SDL_pandora.c
			src/video/pandora/SDL_pandora.h
			src/video/pandora/SDL_pandora_events.c
			src/video/pandora/SDL_pandora_events.h
			src/video/psp/SDL_pspevents.c
			src/video/psp/SDL_pspevents_c.h
			src/video/psp/SDL_pspgl.c
			src/video/psp/SDL_pspgl_c.h
			src/video/psp/SDL_pspvideo.c
			src/video/psp/SDL_pspvideo.h
			src/video/raspberry/SDL_rpievents.c
			src/video/raspberry/SDL_rpievents_c.h
			src/video/raspberry/SDL_rpimouse.c
			src/video/raspberry/SDL_rpimouse.h
			src/video/raspberry/SDL_rpiopengles.c
			src/video/raspberry/SDL_rpiopengles.h
			src/video/raspberry/SDL_rpivideo.c
			src/video/raspberry/SDL_rpivideo.h
			src/video/uikit/SDL_uikitappdelegate.h
			src/video/uikit/SDL_uikitappdelegate.m
			src/video/uikit/SDL_uikitevents.h
			src/video/uikit/SDL_uikitevents.m
			src/video/uikit/SDL_uikitmessagebox.h
			src/video/uikit/SDL_uikitmessagebox.m
			src/video/uikit/SDL_uikitmodes.h
			src/video/uikit/SDL_uikitmodes.m
			src/video/uikit/SDL_uikitopengles.h
			src/video/uikit/SDL_uikitopengles.m
			src/video/uikit/SDL_uikitopenglview.h
			src/video/uikit/SDL_uikitopenglview.m
			src/video/uikit/SDL_uikitvideo.h
			src/video/uikit/SDL_uikitvideo.m
			src/video/uikit/SDL_uikitview.h
			src/video/uikit/SDL_uikitview.m
			src/video/uikit/SDL_uikitviewcontroller.h
			src/video/uikit/SDL_uikitviewcontroller.m
			src/video/uikit/SDL_uikitwindow.h
			src/video/uikit/SDL_uikitwindow.m
			src/video/uikit/keyinfotable.h
			src/video/windows/SDL_msctf.h
			src/video/windows/SDL_vkeys.h
			src/video/windows/SDL_windowsclipboard.c
			src/video/windows/SDL_windowsclipboard.h
			src/video/windows/SDL_windowsevents.c
			src/video/windows/SDL_windowsevents.h
			src/video/windows/SDL_windowsframebuffer.c
			src/video/windows/SDL_windowsframebuffer.h
			src/video/windows/SDL_windowskeyboard.c
			src/video/windows/SDL_windowskeyboard.h
			src/video/windows/SDL_windowsmessagebox.c
			src/video/windows/SDL_windowsmessagebox.h
			src/video/windows/SDL_windowsmodes.c
			src/video/windows/SDL_windowsmodes.h
			src/video/windows/SDL_windowsmouse.c
			src/video/windows/SDL_windowsmouse.h
			src/video/windows/SDL_windowsopengl.c
			src/video/windows/SDL_windowsopengl.h
			src/video/windows/SDL_windowsshape.c
			src/video/windows/SDL_windowsshape.h
			src/video/windows/SDL_windowsvideo.c
			src/video/windows/SDL_windowsvideo.h
			src/video/windows/SDL_windowswindow.c
			src/video/windows/SDL_windowswindow.h
			src/video/windows/wmmsg.h
			src/video/x11/SDL_x11clipboard.c
			src/video/x11/SDL_x11clipboard.h
			src/video/x11/SDL_x11dyn.c
			src/video/x11/SDL_x11dyn.h
			src/video/x11/SDL_x11events.c
			src/video/x11/SDL_x11events.h
			src/video/x11/SDL_x11framebuffer.c
			src/video/x11/SDL_x11framebuffer.h
			src/video/x11/SDL_x11keyboard.c
			src/video/x11/SDL_x11keyboard.h
			src/video/x11/SDL_x11messagebox.c
			src/video/x11/SDL_x11messagebox.h
			src/video/x11/SDL_x11modes.c
			src/video/x11/SDL_x11modes.h
			src/video/x11/SDL_x11mouse.c
			src/video/x11/SDL_x11mouse.h
			src/video/x11/SDL_x11opengl.c
			src/video/x11/SDL_x11opengl.h
			src/video/x11/SDL_x11opengles.c
			src/video/x11/SDL_x11opengles.h
			src/video/x11/SDL_x11shape.c
			src/video/x11/SDL_x11shape.h
			src/video/x11/SDL_x11sym.h
			src/video/x11/SDL_x11touch.c
			src/video/x11/SDL_x11touch.h
			src/video/x11/SDL_x11video.c
			src/video/x11/SDL_x11video.h
			src/video/x11/SDL_x11window.c
			src/video/x11/SDL_x11window.h
			src/video/x11/SDL_x11xinput2.c
			src/video/x11/SDL_x11xinput2.h
			src/video/x11/edid-parse.c
			src/video/x11/edid.h
			src/video/x11/imKStoUCS.c
			src/video/x11/imKStoUCS.h)
# STATIC by default if empty, or SHARED
SET(BII_LIB_TYPE )
# Dependencies to other libraries (user2_block2, user3_blockX)
SET(BII_LIB_DEPS latinga_sdl2_interface )
# System included headers
SET(BII_LIB_SYSTEM_HEADERS GL/gl.h OpenGL/gl.h alloca.h assert.h ctype.h d3d9.h dbt.h devguid.h dirent.h emmintrin.h errno.h fcntl.h iconv.h imm.h intrin.h inttypes.h limits.h locale.h malloc.h math.h memory.h mm3dnow.h mmintrin.h mmsystem.h new objbase.h oleauto.h process.h pthread.h regstr.h sched.h semaphore.h setjmp.h shellapi.h shlobj.h signal.h stdarg.h stdbool.h stddef.h stdint.h stdio.h stdlib.h string.h strings.h sys/param.h sys/stat.h sys/time.h sys/types.h time.h unistd.h unknwn.h vector windows.h windowsx.h xmmintrin.h)
# Required include paths
SET(BII_LIB_INCLUDE_PATHS )


# Executables to be created
SET(BII_BLOCK_EXES )

SET(BII_BLOCK_TESTS )
